[build]
  functions = "bot"

# [context.production]
#   command = "yarn start"
#   publish = "public"

# [context.develop]
#   command = "yarn start"
#   publish = "build"

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/stock"
  to = "/.netlify/functions/stock"
  status = 200



# [[redirects]]
#   from = "https://localweather-io.netlify.com/*"
#   to = "https://localweather.io/:splat"
#   status = 301

# [[redirects]]
#   from = "https://dev-localweather-io.netlify.com/*"
#   to = "https://dev.localweather.io/:splat"
#   status = 301

